export const LOAD_RESUMES_LIST = '[RESUME ACTION] LOAD_RESUMES_LIST';
export const LOAD_RESUME_DETAILS = '[RESUME ACTION] LOAD_RESUME_DETAILS';
export const RESUME_UPDATE_SUCCESS = '[RESUME ACTION] RESUME_UPDATE_SUCCESS';
export const RESUME_UPDATE_FAILED = '[RESUME ACTION] RESUME_UPDATE_FAILED';
export const RESUME_CREATE_SUCCESS = '[RESUME ACTION] RESUME_CREATE_SUCCESS';
export const RESUME_CREATE_FAILED = '[RESUME ACTION] RESUME_CREATE_FAILED';
