# Generated by Django 4.0.4 on 2022-05-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='awards',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='certification',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
