# Generated by Django 4.0.4 on 2022-05-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_resume_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='date',
            field=models.DateField(),
        ),
    ]
