# Generated by Django 4.0.4 on 2022-05-22 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0005_alter_resume_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
