# Generated by Django 4.0.4 on 2022-05-24 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0006_resume_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeapp.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100)),
                ('projectDesc', models.TextField()),
                ('projectStartMonth', models.IntegerField()),
                ('projectStartYear', models.IntegerField()),
                ('projectEndMonth', models.IntegerField()),
                ('projectEndYear', models.IntegerField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeapp.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('companyStartMonth', models.IntegerField()),
                ('companyStartYear', models.IntegerField()),
                ('companyEndMonth', models.IntegerField()),
                ('companyEndYear', models.IntegerField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeapp.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('instituteName', models.CharField(max_length=100)),
                ('courseStartMonth', models.IntegerField()),
                ('courseStartYear', models.IntegerField()),
                ('courseEndMonth', models.IntegerField()),
                ('courseEndYear', models.IntegerField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeapp.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('StartMonth', models.IntegerField()),
                ('StartYear', models.IntegerField()),
                ('EndMonth', models.IntegerField()),
                ('EndYear', models.IntegerField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeapp.resume')),
            ],
        ),
    ]
