# Generated by Django 4.0.4 on 2022-05-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0008_rename_skills_skill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certification',
            new_name='Certificate',
        ),
    ]
